apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ghcr.io/kse-movchan/microservice-lab:5d232288f1ab44e42ecbf5aa189eb8e945a5fb07
        ports:
        - containerPort: 3000
