apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ghcr.io/kse-movchan/microservice-lab:cf31e708926ffe6b8686c6e9b42e91eea61a77c1
        ports:
        - containerPort: 3000
