name: Build and Push Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lowercase image name
        shell: pwsh
        run: |
          $IMAGE_LOWER = "${{ env.IMAGE_NAME }}".ToLower()
          
          echo "IMAGE=$IMAGE_LOWER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Log in to GHCR
        shell: pwsh
        run: |
          # Use the built-in GITHUB_TOKEN to authenticate the runner
          $user = "${{ github.actor }}".ToLower()
          "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $user --password-stdin

      - name: Build and Push
        shell: pwsh
        run: |
          docker build -t "${{ env.IMAGE }}:${{ github.sha }}" .
          docker push "${{ env.IMAGE }}:${{ github.sha }}"
